#ifndef MAKECONSENSUS_GLOBAL_H
#define MAKECONSENSUS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MAKECONSENSUS_LIBRARY)
#  define MAKECONSENSUSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAKECONSENSUSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKECONSENSUS_GLOBAL_H
